### ISSUE TITLE
make packaging stage run without error or exception

### ISSUE THREAD

**Issue by DharminB** [HBRS-MAAS/ws18-project-right-brothers#82]
when running `gradle run --args="-packaging"` in develop branch, it produces an exception
```
***  Uncaught Exception for agent loader-agent  ***
java.lang.ArrayIndexOutOfBoundsException: 0
        at org.maas.agents.LoadingBayAgent$PackagingPhaseMessageSender.findReceiver(LoadingBayAgent.java:186)
        at org.maas.agents.LoadingBayAgent$PackagingPhaseMessageSender.action(LoadingBayAgent.java:195)
        at jade.core.behaviours.Behaviour.actionWrapper(Behaviour.java:344)
        at jade.core.Agent$ActiveLifeCycle.execute(Agent.java:1585)
        at jade.core.Agent.run(Agent.java:1524)
        at java.base/java.lang.Thread.run(Thread.java:844)
loader-agent: Terminating.
```

Currently travis does not check the packaging stage as I have commented it out.

**Comment by DRealArun** [comment]
That’s the error because of the missing order aggregator Agent from the delivery stage . Once we create a dummy we can add the packaging test to travis

**Comment by DRealArun** [comment]
The gradle run does not terminate. This is solved by updating the Loading by with the changes from the pull request manually. I mentioned this fact in the pull request that it has dependency on the upstream loading bay pull request.

**Comment by DharminB** [comment]
> The gradle run does not terminate. This is solved by updating the Loading by with the changes from the pull request manually. I mentioned this fact in the pull request that it has dependency on the upstream loading bay pull request.

I do not understand. Is this solvable by us? If not, could you create an issue in upstream regarding this to the team responsible for this? If this is already solved, could you update travis in `develop`?

**Comment by DRealArun** [comment]
Merged the pull request from upstream for loading bay. Please confirm if issue is still seen after this. If not then, this issue can be closed .
